"""Stable public API for pretrained vision checkpoints and embedding extraction."""

from .embeddings import (
    FeatureExtractor,
    IdentityHead,
    as_feature_extractor,
    extract_embeddings,
    extract_embeddings_batched,
    infer_embedding_dim,
)
from .pretrained_api import (
    AutoFamily,
    Family,
    default_pretrained_checkpoint,
    infer_pretrained_family,
    load_pretrained,
    load_pretrained_resnet,
    load_pretrained_vit,
    load_pretrained_vgg,
    load_pretrained_convnext,
    load_pretrained_efficientnet,
    load_pretrained_swin,
    load_pretrained_inception,
    load_pretrained_vit_resnet_backbone,
    load_pretrained_dino,
    load_pretrained_unet_encoder,
)

__all__ = [
    "AutoFamily",
    "Family",
    "default_pretrained_checkpoint",
    "infer_pretrained_family",
    "load_pretrained",
    "load_pretrained_resnet",
    "load_pretrained_vit",
    "load_pretrained_vgg",
    "load_pretrained_convnext",
    "load_pretrained_efficientnet",
    "load_pretrained_swin",
    "load_pretrained_inception",
    "load_pretrained_vit_resnet_backbone",
    "load_pretrained_dino",
    "load_pretrained_unet_encoder",
    "IdentityHead",
    "FeatureExtractor",
    "as_feature_extractor",
    "extract_embeddings",
    "extract_embeddings_batched",
    "infer_embedding_dim",
]
