"""Stable public API for pretrained vision checkpoints and optional spectral surgery."""

from .pretrained_api import (
    AutoFamily,
    Family,
    default_pretrained_checkpoint,
    infer_pretrained_family,
    load_pretrained,
    load_pretrained_model,
    load_pretrained_resnet,
    load_pretrained_vit,
    load_pretrained_vgg,
    load_pretrained_convnext,
    load_pretrained_efficientnet,
    load_pretrained_swin,
    load_pretrained_inception,
    load_pretrained_vit_resnet_backbone,
    load_pretrained_dino,
    load_pretrained_unet_encoder,
)
from .replace_layers_api import (
    spectralize_and_warmstart_resnet,
    spectralize_and_warmstart_unet_encoder,
    spectralize_and_warmstart_vgg,
    spectralize_and_warmstart_vit,
    spectralize_and_warmstart_dino,
    spectralize_and_warmstart_convnext,
    spectralize_and_warmstart_efficientnet,
    spectralize_and_warmstart_swin,
)

__all__ = [
    "AutoFamily",
    "Family",
    "default_pretrained_checkpoint",
    "infer_pretrained_family",
    "load_pretrained",
    "load_pretrained_model",
    "load_pretrained_resnet",
    "load_pretrained_vit",
    "load_pretrained_vgg",
    "load_pretrained_convnext",
    "load_pretrained_efficientnet",
    "load_pretrained_swin",
    "load_pretrained_inception",
    "load_pretrained_vit_resnet_backbone",
    "load_pretrained_dino",
    "load_pretrained_unet_encoder",
    "spectralize_and_warmstart_resnet",
    "spectralize_and_warmstart_unet_encoder",
    "spectralize_and_warmstart_vgg",
    "spectralize_and_warmstart_vit",
    "spectralize_and_warmstart_dino",
    "spectralize_and_warmstart_convnext",
    "spectralize_and_warmstart_efficientnet",
    "spectralize_and_warmstart_swin",
]
