from setuptools import find_packages, setup

setup(
    name="quantbayes",
    version="0.1.1",
    description="A library for probabilistic and Bayesian machine learning models",
    author="Joseph Margaryan",
    author_email="josephmargaryan@gmail.com",
    url="https://github.com/josephmargaryan/quantbayes",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.26.4",
        "numpyro>=0.18.0",
        "jax>=0.5.2",
        "jaxlib>=0.5.1",
        "torch>=2.6.0",
        "matplotlib>=3.10.1",
        "seaborn>=0.13.2",
        "pandas>=2.2.3",
        "optax>=0.2.4",
        "diffrax>=0.7.0",
        "funsor>=0.4.5",
        "einops>=0.8.0",
        "arviz>=0.21.0",
        "optuna>=4.2.1",
        "xgboost>=3.0.0",
        "lightgbm>=4.6.0",
        "catboost>=1.2.7",
        "scikit-learn>=1.6.1",
        "equinox>=0.11.12",
    ],
    python_requires=">=3.8",
)
